{{- if .Values.initSecrets.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initSecrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  init-secrets: |
    {{- include (print $.Template.BasePath "/diracx/init-secrets/_init-secrets.sh.tpl") . | nindent 4 }}
{{- end -}}
