{{- if .Values.initSecrets.enabled }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "initSecrets.jobname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  ttlSecondsAfterFinished: {{ .Values.global.batchJobTTL }}
  activeDeadlineSeconds: {{ .Values.global.activeDeadlineSeconds }}
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.initSecrets.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "initSecrets.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: ghcr.io/diracgrid/diracx/secret-generation:latest
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args: ["/bin/bash", "/scripts/init-secrets"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          resources:
            {{- toYaml .Values.initSecrets.resources | nindent 12 }}
      volumes:
      - name: scripts
        configMap:
          name: {{ template "initSecrets.fullname" . }}
{{- end }}
