{{- if and .Values.initSecrets.enabled .Values.initSecrets.rbac.create -}}
{{-   if .Values.initSecrets.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "initSecrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{-   end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "initSecrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "initSecrets.name" . }}
    chart: initSecrets-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "initSecrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "initSecrets.name" . }}
    chart: initSecrets-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "initSecrets.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "initSecrets.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end}}
