{{- if .Values.developer.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initCs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  init-cs: |
    {{- include (print $.Template.BasePath "/diracx/init-cs/_init-cs.sh.tpl") . | nindent 4 }}
{{- end -}}
