apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-diracx-dbs
data:
  # Create the databases for DiracX and grant privileges
  init-diracx-dbs.sql: |
{{- range $dbName, $dbSettings := .Values.diracx.sqlDbs.dbs }}
    SELECT 'CREATE DATABASE "{{ $dbName }}"'
    WHERE NOT EXISTS (
      SELECT FROM pg_database
      WHERE datname = '{{ $dbName }}'
    );\gexec

    \c "{{ $dbName }}";

    ALTER DEFAULT PRIVILEGES
    FOR USER postgres
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLES
    TO "{{ $.Values.postgresql.auth.username }}";

    GRANT CONNECT, TEMPORARY
    ON DATABASE "{{ $dbName }}"
    TO "{{ $.Values.postgresql.auth.username }}";
{{- end }}
