apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "diracx.fullname" . }}-certmanager
  namespace: {{ $.Release.Namespace }}
data:
  create-issuer: |
{{ include (print $.Template.BasePath "/_create_issuer.sh.tpl") . | indent 4 }}
  issuer.yml: |
{{ include (print $.Template.BasePath "/_issuer.yaml") . | indent 4 }}
