{{ if .Values.developer.enabled  }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cs-store
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.developer.localCSPath }}
---
{{ end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs-store
spec:
{{ if .Values.developer.enabled  }}
  volumeName: pv-cs-store
{{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
