apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diracx.fullname" . }}
  labels:
    {{- include "diracx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diracx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/settings: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/entrypoint: {{ include (print $.Template.BasePath "/diracx-container-entrypoint.yaml") . | sha256sum }}
      labels:
        {{- include "diracx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diracx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cs-store-mount
          {{- if and (.Values.developer.enabled) (.Values.developer.localCSPath) }}
          persistentVolumeClaim:
            claimName: pvc-cs-store
          {{- else }}
          emptyDir:
          sizeLimit: 5Mi
          {{- end }}
        {{- if and .Values.developer.enabled .Values.developer.modulesToInstall }}
        - name: diracx-code-mount
          persistentVolumeClaim:
            claimName: pvc-diracx-code
        {{- range $module := .Values.developer.modulesToInstall }}
        - name: {{ lower $module }}-editable-install
          empty-dir:
          sizeLimit: 5Mi
        {{- end }}
        {{- end }}
        - name: container-entrypoint
          configMap:
            name: diracx-container-entrypoint
        - name: signing-key-mount
          emptyDir:
          sizeLimit: 5Mi
      initContainers:
      - name: init-cs
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["bash", "/entrypoint.sh"]
        args:
          - "dirac"
          - "internal"
          - "generate-cs"
          - "/cs_store/initialRepo"
          - "--vo=diracAdmin"
          - "--user-group=admin"
          - "--idp-url={{ .Values.dex.config.issuer }}"
          {{- with (first .Values.dex.config.staticClients) }}
          - "--idp-client-id={{ .id }}"
          {{- end }}
        volumeMounts:
          - mountPath: /cs_store
            name: cs-store-mount
            readOnly: false
          {{- if and .Values.developer.enabled .Values.developer.modulesToInstall }}
          - mountPath: {{ .Values.developer.sourcePath }}
            name: diracx-code-mount
            readOnly: true
          {{- range $module := .Values.developer.modulesToInstall }}
          - mountPath: "{{ $.Values.developer.sourcePath }}/{{ $module }}/src/{{ $module }}.egg-info"
            name: {{ lower $module }}-editable-install
            readOnly: false
          {{- end }}
          {{- end }}
          - name: container-entrypoint
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
      - name: init-cs-user
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["bash", "/entrypoint.sh"]
        args:
          - "dirac"
          - "internal"
          - "add-user"
          - "/cs_store/initialRepo"
          - "--vo=diracAdmin"
          - "--user-group=admin"
          - "--sub=EgVsb2NhbA"
        volumeMounts:
          - mountPath: /cs_store
            name: cs-store-mount
            readOnly: false
          {{- if and .Values.developer.enabled .Values.developer.modulesToInstall }}
          - mountPath: {{ .Values.developer.sourcePath }}
            name: diracx-code-mount
            readOnly: true
          {{- range $module := .Values.developer.modulesToInstall }}
          - mountPath: "{{ $.Values.developer.sourcePath }}/{{ $module }}/src/{{ $module }}.egg-info"
            name: {{ lower $module }}-editable-install
            readOnly: false
          {{- end }}
          {{- end }}
          - name: container-entrypoint
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
      - name: init-signing-key
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: [/dockerMicroMambaEntrypoint.sh]
        args:
          - "ssh-keygen"
          - "-P"
          - ""
          - "-trsa"
          - "-b4096"
          - "-mPEM"
          - "-f/signing-key/rs256.key"
        volumeMounts:
          - mountPath: /signing-key/
            name: signing-key-mount
            readOnly: false
      {{- if .Values.diracx.manageSQLSchema }}
      - name: create-sql-db-schema
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["bash", "/entrypoint.sh"]
        args: ["python", "-m", "diracx.db", "init-sql"]
        volumeMounts:
          {{- if and .Values.developer.enabled .Values.developer.modulesToInstall }}
          - mountPath: {{ .Values.developer.sourcePath }}
            name: diracx-code-mount
            readOnly: true
          {{- range $module := .Values.developer.modulesToInstall }}
          - mountPath: "{{ $.Values.developer.sourcePath }}/{{ $module }}/src/{{ $module }}.egg-info"
            name: {{ lower $module }}-editable-install
            readOnly: false
          {{- end }}
          {{- end }}
          - name: container-entrypoint
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
        envFrom:
          - secretRef:
              name: diracx-init-mysql-secrets
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs/
              port: http
          readinessProbe:
            httpGet:
              path: /docs/
              port: http
          command: ["bash", "/entrypoint.sh"]
          args:
            - uvicorn
            - --factory
            - diracx.routers:create_app
            - --host=0.0.0.0
            - --port=8000
          {{- if .Values.developer.enabled }}
            - "--reload"
            - "--proxy-headers"
            {{- if .Values.developer.modulesToInstall }}
            - "--reload-dir={{ .Values.developer.sourcePath }}"
            {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /cs_store
              name: cs-store-mount
              readOnly: true
            - mountPath: /signing-key/
              name: signing-key-mount
              readOnly: true
            {{- if and .Values.developer.enabled .Values.developer.modulesToInstall }}
            - mountPath: {{ .Values.developer.sourcePath }}
              name: diracx-code-mount
              readOnly: true
            {{- range $module := .Values.developer.modulesToInstall }}
            - mountPath: "{{ $.Values.developer.sourcePath }}/{{ $module }}/src/{{ $module }}.egg-info"
              name: {{ lower $module }}-editable-install
              readOnly: false
            {{- end }}
            {{- end }}
            - name: container-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
          envFrom:
            # - configMapRef:
            #     name: diracx-env-config
            - secretRef:
                name: diracx-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
