{{- if .Values.developer.enabled  }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-diracx-code
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.developer.sourcePath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-diracx-code
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
spec:
  storageClassName: ""
  volumeName: pv-diracx-code
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
