apiVersion: v1
kind: ConfigMap
metadata:
  name: diracx-container-entrypoint
data:
  entrypoint.sh: |
    #!/bin/bash
    set -euo pipefail
    IFS=$'\n\t'

    ulimit -n 8192
    eval "$(micromamba shell hook --shell=posix)" && micromamba activate base

    {{ if .Values.developer.sourcePath }}
    pip install {{- range $moduleName := .Values.developer.modulesToInstall }} -e {{ $.Values.developer.sourcePath }}/{{ $moduleName }} {{- end }}
    {{- end }}

    exec "$@"
