{{- $fullName := include "diracx.fullname" . }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "diracx.labels" . | nindent 4 }}
  annotations:
  {{- if index .Values "cert-manager-issuer" "enabled" }}
    cert-manager.io/issuer: diracx-ca-issuer
  {{- end }}
  {{ with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - hosts:
    - {{ required "diracx.hostname must be set!" .Values.diracx.hostname }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ required "diracx.hostname must be set!" .Values.diracx.hostname }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.diracx.service.port }}
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.diracx.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  number: {{ .Values.diracxWeb.service.port }}
{{- end }}
