apiVersion: v1
kind: Secret
metadata:
  name: diracx-secrets
stringData:
{{ .Values.diracx.settings | toYaml | indent 2 }}
{{- if and .Values.developer.enabled .Values.opensearch.enabled }}
  {{- range $dbName := .Values.diracx.osDatabases }}
  DIRACX_OS_DB_{{ $dbName | upper }}: '{"hosts": "admin:admin@opensearch-cluster-master:9200", "use_ssl": true, "verify_certs": false}'
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: diracx-web-secrets
stringData:
{{ .Values.diracxWeb.settings | toYaml | indent 2 }}
---
{{- if .Values.diracx.manageSQLSchema.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: diracx-init-mysql-secrets
stringData:
{{ .Values.diracx.manageSQLSchema.env | toYaml | indent 2 }}
---
{{- end }}
{{- if .Values.diracx.manageOSIndices }}
apiVersion: v1
kind: Secret
metadata:
  name: diracx-init-os-secrets
stringData:
{{- if and .Values.developer.enabled .Values.opensearch.enabled }}
  {{- range $dbName := .Values.diracx.osDatabases }}
  DIRACX_OS_DB_{{ $dbName | upper }}: '{"hosts": "admin:admin@opensearch-cluster-master:9200", "use_ssl": true, "verify_certs": false}'
  {{- end }}
{{- end }}
{{- end }}
