apiVersion: v1
kind: Secret
metadata:
  name: diracx-secrets
stringData:
{{ .Values.diracx.settings | toYaml | indent 2 }}
---
{{- if index .Values "init-sql" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: diracx-init-mysql-secrets
stringData:
{{ (index .Values "init-sql" "env") | toYaml | indent 2 }}
---
{{- end }}

{{- if .Values.initOs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: diracx-init-os-secrets
stringData:
{{ .Values.initOs.env | toYaml | indent 2 }}
---
{{- end }}
