{{- if .Values.initOs.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initOs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  init-os: |
    {{- include (print $.Template.BasePath "/diracx/init-os/_init-os.sh.tpl") . | nindent 4 }}
{{- end -}}
